name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - test
  pull_request:
    branches:
      - main

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Configure Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Log in to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 4: Run functional tests tied to CI
      - name: Run functional tests
        run: |
          cd analysis-avatar-ms && npm install && npm test
          cd ../login-ms && npm install && npm test
          cd ../recovery-ms && npm install && npm test
          cd ../register-ms && npm install && npm test
          cd ../reset-ms && npm install && npm test

      # Step 5: Build and upload the image to Docker Hub
      - name: Build and push Docker images
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml push

      # Step 6: Deploy to QA (if the branch is `test`)
      - name: Deploy to EC2 QA
        if: github.ref == 'refs/heads/test'
        run: |
          echo "Deploying to QA EC2 instance..."
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_KEY_QA }} ec2-user@${{ secrets.EC2_QA }} << 'EOF'
            cd /path/to/deployment/directory
            docker pull alexismendozaa/auth-service:latest
            docker-compose -f docker-compose.yml up -d
          EOF

      # Step 7: Deploy to Production (if the branch is `main` or a PR to `main`)
      - name: Deploy to EC2 PROD
        if: github.ref == 'refs/heads/main' || github.event.pull_request.base.ref == 'main'
        run: |
          echo "Deploying to PROD EC2 instance..."
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_KEY_PROD }} ec2-user@${{ secrets.EC2_PROD }} << 'EOF'
            cd /path/to/deployment/directory
            docker pull alexismendozaa/auth-service:latest
            docker-compose -f docker-compose.yml up -d
          EOF
