name: Docker Build and Deploy

on:
  push:
    branches:
      - test

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    # Step 1: Checkout the code
    - name: Check out code
      uses: actions/checkout@v2

    # Step 2: Log in to Docker Hub before building images
    - name: Log in to Docker Hub
      run: |
        echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    # Step 3: Install Docker Compose
    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    # Step 4: Install dependencies and run tests for each microservice
    - name: Install dependencies and run tests for all microservices
      run: |
        # Install dependencies and test for login-ms
        cd login-ms
        npm install
        npm test

        # Install dependencies and test for register-ms
        cd ../register-ms
        npm install
        npm test

        # Install dependencies and test for reset-ms
        cd ../reset-ms
        npm install
        npm test

        # Install dependencies and test for recovery-ms
        cd ../recovery-ms
        npm install
        npm test

        # Install dependencies and test for analysis-avatar-ms
        cd ../analysis-avatar-ms
        npm install
        npm test

    # Step 5: Build Docker images using Docker Compose
    - name: Build Docker images using Docker Compose
      run: |
        docker-compose -f docker-compose.yml build

    # Step 6: Push Docker images to Docker Hub
    - name: Push Docker images to Docker Hub
      run: |
        docker-compose -f docker-compose.yml push

    # Step 7: Connect to EC2, stop and remove existing containers
    - name: Clean up existing containers on EC2
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_QA }}
        username: ubuntu
        key: ${{ secrets.SSH_KEY_QA }}
        port: 22
        debug: true
        script: |
          # Stop and remove existing containers
          docker stop $(docker ps -aq) || true
          docker rm $(docker ps -aq) || true
          docker system prune -af || true

    # Step 8: Connect to EC2 and deploy the new containers from Docker Hub
    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_QA }}  # Use the EC2 public IP (EC2_QA secret)
        username: ubuntu  # User
        key: ${{ secrets.SSH_KEY_QA }}  # Use SSH_KEY_QA secret (private key)
        port: 22
        debug: true  # Enable debugging for more details
        script: |
          # Export environment variables for each container
          
          # Common environment variables
          export DB_HOST=${{ secrets.DB_HOST }}
          export DB_USER=${{ secrets.DB_USER }}
          export DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          export DB_NAME=${{ secrets.DB_NAME }}
          export JWT_SECRET=${{ secrets.JWT_SECRET }}
          export JWT_EXPIRATION=${{ secrets.JWT_EXPIRATION }}
          export S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }}
          export AWS_REGION=${{ secrets.AWS_REGION }}
          export SIGHTENGINE_API_KEY=${{ secrets.SIGHTENGINE_API_KEY }}
          export SIGHTENGINE_API_USER=${{ secrets.SIGHTENGINE_API_USER }}
          export EMAIL_USER=${{ secrets.EMAIL_USER }}
          export EMAIL_PASS=${{ secrets.EMAIL_PASS }}
          export APP_URL=${{ secrets.APP_URL }}

          # Run containers for each microservice
          docker run -d --name analysis-avatar-ms \
            -p 5029:3029 \
            -e DB_HOST=${{ secrets.DB_HOST }} \
            -e DB_USER=${{ secrets.DB_USER }} \
            -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            -e DB_NAME=${{ secrets.DB_NAME }} \
            -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
            -e JWT_EXPIRATION=${{ secrets.JWT_EXPIRATION }} \
            -e S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }} \
            -e AWS_REGION=${{ secrets.AWS_REGION }} \
            -e SIGHTENGINE_API_KEY=${{ secrets.SIGHTENGINE_API_KEY }} \
            -e SIGHTENGINE_API_USER=${{ secrets.SIGHTENGINE_API_USER }} \
            ${{ secrets.DOCKERHUB_USERNAME }}/analysis-avatar-ms:latest

          docker run -d --name login-ms \
            -p 5001:3001 \
            -e DB_HOST=${{ secrets.DB_HOST }} \
            -e DB_USER=${{ secrets.DB_USER }} \
            -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            -e DB_NAME=${{ secrets.DB_NAME }} \
            -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
            -e JWT_EXPIRATION=${{ secrets.JWT_EXPIRATION }} \
            -e S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }} \
            -e S3_ACCESS_KEY_ID=${{ secrets.S3_ACCESS_KEY_ID }} \
            -e S3_SECRET_ACCESS_KEY=${{ secrets.S3_SECRET_ACCESS_KEY }} \
            ${{ secrets.DOCKERHUB_USERNAME }}/login-ms:latest

          docker run -d --name recovery-ms \
            -p 5002:3002 \
            -e DB_HOST=${{ secrets.DB_HOST }} \
            -e DB_USER=${{ secrets.DB_USER }} \
            -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            -e DB_NAME=${{ secrets.DB_NAME }} \
            -e EMAIL_USER=${{ secrets.EMAIL_USER }} \
            -e EMAIL_PASS=${{ secrets.EMAIL_PASS }} \
            -e APP_URL=${{ secrets.APP_URL }} \
            ${{ secrets.DOCKERHUB_USERNAME }}/recovery-ms:latest

          docker run -d --name register-ms \
            -p 5025:3025 \
            -e DB_HOST=${{ secrets.DB_HOST }} \
            -e DB_USER=${{ secrets.DB_USER }} \
            -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            -e DB_NAME=${{ secrets.DB_NAME }} \
            -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
            -e JWT_EXPIRATION=${{ secrets.JWT_EXPIRATION }} \
            -e S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }} \
            -e AWS_REGION=${{ secrets.AWS_REGION }} \
            ${{ secrets.DOCKERHUB_USERNAME }}/register-ms:latest

          docker run -d --name reset-ms \
            -p 5003:3003 \
            -e DB_HOST=${{ secrets.DB_HOST }} \
            -e DB_USER=${{ secrets.DB_USER }} \
            -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            -e DB_NAME=${{ secrets.DB_NAME }} \
            -e EMAIL_USER=${{ secrets.EMAIL_USER }} \
            -e EMAIL_PASS=${{ secrets.EMAIL_PASS }} \
            ${{ secrets.DOCKERHUB_USERNAME }}/reset-ms:latest
