name: Register Service CI/CD

on:
  push:
    branches: [test]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./register-ms
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/register-ms:latest

  deploy-to-ec2:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2_key.pem
          chmod 600 ~/.ssh/ec2_key.pem
          ssh-keyscan ${{ secrets.REGISTER_EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/ec2_key.pem ec2-user@${{ secrets.REGISTER_EC2_HOST }} << 'EOF'
          # Detener y eliminar contenedor anterior si existe
          docker stop register-ms || true
          docker rm register-ms || true
          
          # Descargar la imagen que acabamos de subir a Docker Hub
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/register-ms:latest
          
          # Ejecutar la nueva imagen
          docker run -d \
            --name register-ms \
            -p 8080:8080 \
            --restart unless-stopped \
            ${{ secrets.DOCKERHUB_USERNAME }}/register-ms:latest
          EOF