name: Reset Service CI/CD

on:
  push:
    branches: [test]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./reset-ms      
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/reset-ms:latest

  deploy-to-ec2:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2_key
          chmod 600 ~/.ssh/ec2_key
          ssh-keyscan ${{ secrets.RESET_EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Verify SSH connection
        run: ssh -i ~/.ssh/ec2_key ubuntu@${{ secrets.RESET_EC2_HOST }} "echo 'SSH connection successful!'"

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/ec2_key ubuntu@${{ secrets.RESET_EC2_HOST }} << 'EOF'
          sudo docker stop reset-ms || true
          sudo docker rm reset-ms || true

          sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/reset-ms:latest

          sudo docker run -d \
            --name reset-ms \
            -p 8003:3003 \
            --restart unless-stopped \
            -e APP_URL=${{ secrets.APP_URL }} \
            -e DB_HOST=${{ secrets.DB_HOST }} \
            -e DB_NAME=${{ secrets.DB_NAME }} \
            -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            -e DB_USER=${{ secrets.DB_USER }} \
            -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
            -e JWT_EXPIRATION=${{ secrets.JWT_EXPIRATION }} \
            -e EMAIL_USER=${{ secrets.EMAIL_USER }} \
            -e EMAIL_PASS=${{ secrets.EMAIL_PASS }} \
            -e S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }} \
            ${{ secrets.DOCKERHUB_USERNAME }}/reset-ms:latest

          sudo docker ps | grep reset-ms
          EOF
